// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHr5ZeBuaTNhy1JU-85aEz0wWWX2wYWqQ',
    appId: '1:402197539522:web:d6895d169c17f1d738295b',
    messagingSenderId: '402197539522',
    projectId: 'homeworkout-7fe50',
    authDomain: 'homeworkout-7fe50.firebaseapp.com',
    databaseURL: 'https://homeworkout-7fe50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeworkout-7fe50.appspot.com',
    measurementId: 'G-RJHHJQG9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-1vwZB11CpZAz5hwhh57X93xLQLU_KM',
    appId: '1:402197539522:android:da986062bc62fd5638295b',
    messagingSenderId: '402197539522',
    projectId: 'homeworkout-7fe50',
    databaseURL: 'https://homeworkout-7fe50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeworkout-7fe50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9HTGmeXSlhwATYpagJiUZDOOlrqZTxdI',
    appId: '1:402197539522:ios:e8c2f6b220d9267638295b',
    messagingSenderId: '402197539522',
    projectId: 'homeworkout-7fe50',
    databaseURL: 'https://homeworkout-7fe50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeworkout-7fe50.appspot.com',
    androidClientId: '402197539522-2rst8e8tn5bhl2ar9gt88e6hc2ukkknv.apps.googleusercontent.com',
    iosClientId: '402197539522-cvd3j8s4v58deprec4dfrshr51pq63q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeWorkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9HTGmeXSlhwATYpagJiUZDOOlrqZTxdI',
    appId: '1:402197539522:ios:ae4f5773ca6deac638295b',
    messagingSenderId: '402197539522',
    projectId: 'homeworkout-7fe50',
    databaseURL: 'https://homeworkout-7fe50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeworkout-7fe50.appspot.com',
    androidClientId: '402197539522-2rst8e8tn5bhl2ar9gt88e6hc2ukkknv.apps.googleusercontent.com',
    iosClientId: '402197539522-ughuhcb63buasfevn144j9kdnknlpfj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeWorkout.RunnerTests',
  );
}
